const FLAG_BY_COUNTRY_CODE: Record<string, string> = {
  CAN: "🇨🇦",
  USA: "🇺🇸",
  RUS: "🇷🇺",
  SWE: "🇸🇪",
  FIN: "🇫🇮",
  CZE: "🇨🇿",
  SVK: "🇸🇰",
  DEU: "🇩🇪",
  CHE: "🇨🇭",
  DNK: "🇩🇰",
  NOR: "🇳🇴",
  FRA: "🇫🇷",
  AUT: "🇦🇹",
  BEL: "🇧🇪",
  GBR: "🇬🇧",
  ITA: "🇮🇹",
  LVA: "🇱🇻",
  POL: "🇵🇱",
  SVN: "🇸🇮",
  AUS: "🇦🇺",
  BLR: "🇧🇾",
  CHN: "🇨🇳",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  UKR: "🇺🇦",
  HUN: "🇭🇺",
  EST: "🇪🇪",
  LTU: "🇱🇹",
  NLD: "🇳🇱",
  ESP: "🇪🇸",
  MEX: "🇲🇽",
  KAZ: "🇰🇿",
  IRL: "🇮🇪",
  NZL: "🇳🇿",
  ZAF: "🇿🇦",
  BRA: "🇧🇷",
};

export function nationalityToFlag(countryCode: string): string {
  return FLAG_BY_COUNTRY_CODE[countryCode] ?? countryCode;
}
