// Generated by scripts/compute-logo-bounds.ts — rerun if a new team joins the league.
import type { ContentBounds } from "../../games/guess-the-logo/logic";

export interface TeamLogoEntry {
  abbrev: string;
  name: string;
  contentBounds: ContentBounds;
}

export const TEAM_LOGOS: TeamLogoEntry[] = [
  {
    "abbrev": "ANA",
    "name": "Ducks d'Anaheim",
    "contentBounds": {
      "x": 0.2935546875,
      "y": 0.22216796875,
      "width": 0.412890625,
      "height": 0.5537109375
    }
  },
  {
    "abbrev": "BOS",
    "name": "Bruins de Boston",
    "contentBounds": {
      "x": 0.2962890625,
      "y": 0.19511718749999998,
      "width": 0.40742187500000004,
      "height": 0.6097656250000001
    }
  },
  {
    "abbrev": "BUF",
    "name": "Sabres de Buffalo",
    "contentBounds": {
      "x": 0.2962890625,
      "y": 0.19511718749999998,
      "width": 0.40742187500000004,
      "height": 0.6097656250000001
    }
  },
  {
    "abbrev": "CGY",
    "name": "Flames de Calgary",
    "contentBounds": {
      "x": 0.300390625,
      "y": 0.2470703125,
      "width": 0.39921875,
      "height": 0.505859375
    }
  },
  {
    "abbrev": "CAR",
    "name": "Hurricanes de la Caroline",
    "contentBounds": {
      "x": 0.2552734375,
      "y": 0.2798828125,
      "width": 0.48945312500000004,
      "height": 0.440234375
    }
  },
  {
    "abbrev": "CHI",
    "name": "Blackhawks de Chicago",
    "contentBounds": {
      "x": 0.2935546875,
      "y": 0.2306640625,
      "width": 0.412890625,
      "height": 0.538671875
    }
  },
  {
    "abbrev": "COL",
    "name": "Avalanche du Colorado",
    "contentBounds": {
      "x": 0.2921875,
      "y": 0.24462890625,
      "width": 0.415625,
      "height": 0.5126953125
    }
  },
  {
    "abbrev": "CBJ",
    "name": "Blue Jackets de Columbus",
    "contentBounds": {
      "x": 0.28125,
      "y": 0.2169921875,
      "width": 0.4375,
      "height": 0.566015625
    }
  },
  {
    "abbrev": "DAL",
    "name": "Stars de Dallas",
    "contentBounds": {
      "x": 0.256640625,
      "y": 0.2005859375,
      "width": 0.48671875,
      "height": 0.598828125
    }
  },
  {
    "abbrev": "DET",
    "name": "Red Wings de Detroit",
    "contentBounds": {
      "x": 0.2525390625,
      "y": 0.2251953125,
      "width": 0.494921875,
      "height": 0.549609375
    }
  },
  {
    "abbrev": "EDM",
    "name": "Oilers d'Edmonton",
    "contentBounds": {
      "x": 0.2935546875,
      "y": 0.191015625,
      "width": 0.412890625,
      "height": 0.61796875
    }
  },
  {
    "abbrev": "FLA",
    "name": "Panthers de la Floride",
    "contentBounds": {
      "x": 0.325,
      "y": 0.207421875,
      "width": 0.35,
      "height": 0.58515625
    }
  },
  {
    "abbrev": "LAK",
    "name": "Kings de Los Angeles",
    "contentBounds": {
      "x": 0.2361328125,
      "y": 0.24843749999999998,
      "width": 0.527734375,
      "height": 0.503125
    }
  },
  {
    "abbrev": "MIN",
    "name": "Wild du Minnesota",
    "contentBounds": {
      "x": 0.2552734375,
      "y": 0.2634765625,
      "width": 0.48945312500000004,
      "height": 0.473046875
    }
  },
  {
    "abbrev": "MTL",
    "name": "Canadien de Montréal",
    "contentBounds": {
      "x": 0.259375,
      "y": 0.25390625,
      "width": 0.48125,
      "height": 0.4921875
    }
  },
  {
    "abbrev": "NJD",
    "name": "Devils du New Jersey",
    "contentBounds": {
      "x": 0.311328125,
      "y": 0.21015625,
      "width": 0.37734375,
      "height": 0.5796875
    }
  },
  {
    "abbrev": "NYI",
    "name": "Islanders de New York",
    "contentBounds": {
      "x": 0.3072265625,
      "y": 0.22109374999999998,
      "width": 0.385546875,
      "height": 0.5578125
    }
  },
  {
    "abbrev": "NYR",
    "name": "Rangers de New York",
    "contentBounds": {
      "x": 0.3181640625,
      "y": 0.2388671875,
      "width": 0.363671875,
      "height": 0.522265625
    }
  },
  {
    "abbrev": "NSH",
    "name": "Predators de Nashville",
    "contentBounds": {
      "x": 0.273046875,
      "y": 0.2990234375,
      "width": 0.45390625,
      "height": 0.401953125
    }
  },
  {
    "abbrev": "OTT",
    "name": "Sénateurs d'Ottawa",
    "contentBounds": {
      "x": 0.259375,
      "y": 0.212890625,
      "width": 0.48125,
      "height": 0.57421875
    }
  },
  {
    "abbrev": "PHI",
    "name": "Flyers de Philadelphie",
    "contentBounds": {
      "x": 0.2921875,
      "y": 0.283984375,
      "width": 0.415625,
      "height": 0.43203125
    }
  },
  {
    "abbrev": "PIT",
    "name": "Penguins de Pittsburgh",
    "contentBounds": {
      "x": 0.2962890625,
      "y": 0.21015625,
      "width": 0.40742187500000004,
      "height": 0.5796875
    }
  },
  {
    "abbrev": "SJS",
    "name": "Sharks de San Jose",
    "contentBounds": {
      "x": 0.26787109375,
      "y": 0.20908203125,
      "width": 0.4662109375,
      "height": 0.5837890625
    }
  },
  {
    "abbrev": "SEA",
    "name": "Kraken de Seattle",
    "contentBounds": {
      "x": 0.3455078125,
      "y": 0.2087890625,
      "width": 0.308984375,
      "height": 0.582421875
    }
  },
  {
    "abbrev": "STL",
    "name": "Blues de St. Louis",
    "contentBounds": {
      "x": 0.2990234375,
      "y": 0.262109375,
      "width": 0.401953125,
      "height": 0.47578125000000004
    }
  },
  {
    "abbrev": "TBL",
    "name": "Lightning de Tampa Bay",
    "contentBounds": {
      "x": 0.2921875,
      "y": 0.20849609375,
      "width": 0.415625,
      "height": 0.5810546875
    }
  },
  {
    "abbrev": "TOR",
    "name": "Maple Leafs de Toronto",
    "contentBounds": {
      "x": 0.3126953125,
      "y": 0.18720703125,
      "width": 0.374609375,
      "height": 0.6275390625
    }
  },
  {
    "abbrev": "UTA",
    "name": "Mammoth de l'Utah",
    "contentBounds": {
      "x": 0.24843749999999998,
      "y": 0.2224609375,
      "width": 0.503125,
      "height": 0.555078125
    }
  },
  {
    "abbrev": "VAN",
    "name": "Canucks de Vancouver",
    "contentBounds": {
      "x": 0.2908203125,
      "y": 0.20195312499999998,
      "width": 0.418359375,
      "height": 0.5960937500000001
    }
  },
  {
    "abbrev": "VGK",
    "name": "Golden Knights de Vegas",
    "contentBounds": {
      "x": 0.3509765625,
      "y": 0.1978515625,
      "width": 0.29804687500000004,
      "height": 0.604296875
    }
  },
  {
    "abbrev": "WSH",
    "name": "Capitals de Washington",
    "contentBounds": {
      "x": 0.2388671875,
      "y": 0.24951171875,
      "width": 0.522265625,
      "height": 0.4990234375
    }
  },
  {
    "abbrev": "WPG",
    "name": "Jets de Winnipeg",
    "contentBounds": {
      "x": 0.2908203125,
      "y": 0.185546875,
      "width": 0.418359375,
      "height": 0.62890625
    }
  }
];
