// scripts/compute-logo-bounds.ts
import { writeFileSync } from "node:fs";
import sharp from "sharp";
import { teamLogoUrl } from "../src/lib/team-logo.ts";
import { TEAM_LOGOS } from "../src/data/curated/team-logos.ts";
import type { ContentBounds } from "../src/games/guess-the-logo/logic.ts";

// Rasterizing at a fixed resolution only affects precision, not the
// resulting fractional bounds: resizing a non-square SVG to a square with
// fit "fill" stretches each axis independently, which does not change
// where content falls as a FRACTION of that axis.
const RENDER_SIZE = 512;
const ALPHA_THRESHOLD = 10; // ignore near-fully-transparent anti-aliasing fringe

// Shrinks the tight alpha bounding box inward so the daily focus point
// lands well inside the logo's visual mass rather than on a thin edge
// (e.g. the tip of a leaf outline), which would look almost as empty as
// true transparent space at 5x zoom.
const INSET_RATIO = 0.15;

async function computeAlphaBounds(svgUrl: string): Promise<ContentBounds> {
  const res = await fetch(svgUrl);
  if (!res.ok) throw new Error(`Failed to fetch ${svgUrl}: ${res.status}`);
  const svgBuffer = Buffer.from(await res.arrayBuffer());

  const { data, info } = await sharp(svgBuffer)
    .resize(RENDER_SIZE, RENDER_SIZE, { fit: "fill" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  let minX = info.width;
  let minY = info.height;
  let maxX = -1;
  let maxY = -1;

  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      const alpha = data[(y * info.width + x) * info.channels + 3];
      if (alpha > ALPHA_THRESHOLD) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }

  if (maxX < 0) {
    throw new Error(`${svgUrl} rendered fully transparent — cannot compute bounds`);
  }

  return {
    x: minX / info.width,
    y: minY / info.height,
    width: (maxX - minX + 1) / info.width,
    height: (maxY - minY + 1) / info.height,
  };
}

function inset(bounds: ContentBounds): ContentBounds {
  const insetX = bounds.width * INSET_RATIO;
  const insetY = bounds.height * INSET_RATIO;
  return {
    x: bounds.x + insetX,
    y: bounds.y + insetY,
    width: Math.max(bounds.width - insetX * 2, 0.01),
    height: Math.max(bounds.height - insetY * 2, 0.01),
  };
}

async function main() {
  const entries = [];

  for (const team of TEAM_LOGOS) {
    // Assumes the light and dark variants share the same artwork (only
    // recolored), so one variant's bounds apply to both.
    const rawBounds = await computeAlphaBounds(teamLogoUrl(team.abbrev, "dark"));
    const contentBounds = inset(rawBounds);
    entries.push({ abbrev: team.abbrev, name: team.name, contentBounds });
    console.log(`${team.abbrev}: ${JSON.stringify(contentBounds)}`);
  }

  const fileContent = `// Generated by scripts/compute-logo-bounds.ts — the script reads the
// {abbrev, name} pairs already in this file and rewrites it with freshly
// computed contentBounds. If a new team joins the league, hand-add its
// {abbrev, name} entry below first (contentBounds can be a placeholder),
// then rerun the script to fill in the real bounds.
import type { ContentBounds } from "../../games/guess-the-logo/logic";

export interface TeamLogoEntry {
  abbrev: string;
  name: string;
  contentBounds: ContentBounds;
}

export const TEAM_LOGOS: TeamLogoEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  writeFileSync("src/data/curated/team-logos.ts", fileContent);
  console.log(`Done. Wrote ${entries.length} team logo entries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
